24CV WEB/Models/EmailViewModel.cs
namespace _24CV_WEB.Models
{
	public class EmailViewModel
	{
		public string Email { get; set; }
		public string Comentario { get; set; }
	}
}

24CV WEB/Models/ErrorViewModel.cs
namespace _24CV_WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

24CV WEB/Models/InformacionViewModel.cs
using System.Diagnostics;
using System.Drawing;
using System;
using System.Net.Sockets;

namespace _24CV_WEB.Models
{
	public class InformacionViewModel
	{
		public string Nombre { get; set; }
		public string Apellidos { get; set; }
		public string Email { get; set; }
		public DateOnly FechaNacimiento { get; set; }
		public SelectMode Turno { get; set; }
		public enum SelectMode
		{
			Matutino,
			Vespertino
		}
		public string Comentarios { get; set; }
	}

}

24CV WEB/Models/Persona.cs
namespace _24CV_WEB.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNacimiento { get; set; }
    }
}

24CV WEB/Controllers/ContactoController.cs
using _24CV_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace _24CV_WEB.Controllers
{
    public class ContactoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EnviarCorreo(string email, string comentarios)
        {
            TempData["Email"] = email;
            TempData["Comentario"] = comentarios;

            return View("Index");
        }

        public IActionResult EnviarInformacion(EmailViewModel model)
        {
			TempData["Email"] = model.Email;
			TempData["Comentario"] = model.Comentario;

            SendEmail(model.Email, model.Comentario);

			return View("Index", model);
        }

        public bool SendEmail(string email, string comentario)
        {
            MailMessage mail = new MailMessage();

            SmtpClient smtp = new SmtpClient("mail.ulatransfers.com", 465);

            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("info@ulatransfers.com", "LOLOlolo10.");

            mail.From = new MailAddress("info@ulatransfers.com", "Ula Transfers");
            mail.To.Add(email);
            mail.Subject = "Notificacion de contacto.";
            mail.IsBodyHtml = true;
            mail.Body = $"Se ha recibido informacion del correo <h1>{email}</h1> <br> " +
                $"<p>{comentario}</p>";

            smtp.Send(mail);

            return true;
        }
    }
}

24CV WEB/Controllers/EjemplosController.cs
using _24CV_WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace _24CV_WEB.Controllers
{
    public class EjemplosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contacto()
        {
            Persona persona = new Persona();
            persona.Nombre = "Alfredo";
            persona.Apellido = "Casanova";
            persona.FechaNacimiento = DateTime.Now;
            return View(persona);
        }
    }
}

24CV WEB/Controllers/FormularioController.cs
using _24CV_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;
using System.Net.Sockets;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Drawing;


namespace _24CV_WEB.Controllers
{
	public class FormularioController : Controller
	{
		public IActionResult Contacto()
		{
			return View();
		}

		public IActionResult EnviarInformacion(InformacionViewModel model)
		{
			TempData["Nombre"] = model.Nombre;
			TempData["Apellidos"] = model.Apellidos;
			TempData["Email"] = model.Email;
			TempData["FechaNacimiento"] = model.FechaNacimiento;
			TempData["Turno"] = model.Turno;
			TempData["Comentarios"] = model.Comentarios;

			ProcesarSolicitud(model.Nombre, model.Apellidos, model.Email, model.FechaNacimiento, model.Turno, model.Comentarios);

			return View("Contacto", model);
		}

		public bool ProcesarSolicitud(string nombre, string apellidos, string email, DateOnly fechanacimiento, InformacionViewModel.SelectMode turno, string comentario)
		{
			MailMessage mail = new MailMessage();

			SmtpClient smtp = new SmtpClient("mail.ulatransfers.com", 587);

			smtp.EnableSsl = true;
			smtp.UseDefaultCredentials = false;
			smtp.Credentials = new NetworkCredential("info@ulatransfers.com", "LOLOlolo10.");

			mail.From = new MailAddress("info@ulatransfers.com", "Ula Transfers");
			mail.To.Add(email);
			mail.Subject = "Formulario de Contacto";
			mail.IsBodyHtml = true;

			mail.Body = "<body>" +
				$"<p> Nombre: {nombre}</p>" +
				$"<p> Apellidos: {apellidos}</p>" +
				$"<p> Email: {email}</p>" +
				$"<p> Fecha de Nacimiento: {fechanacimiento}</p>" +
				$"<p> Turno: {turno}</p>" +
				$"<p> Comentario: {comentario}</p>" +
				"</body>";


			smtp.Send(mail);

			return true;
		}

	}
}

24CV WEB/Controllers/HomeController.cs
using _24CV_WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace _24CV_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

24CV WEB/Views/Contacto/Index.cshtml
@model _24CV_WEB.Models.EmailViewModel

<div class="row">
	@if (TempData["Email"] != null)
	{
		<div class="alert alert-success">
			<h3>Se ha recibido la informacion del correo @TempData["Email"]</h3> <br>
			<p class="text-sm-center">@TempData["Comentario"]</p>
		</div>
	}


	<div class="col-12">
		<h2 class="text-center">Ejemplo</h2>
		<p class="text-center"></p>
	</div>
	<div class="col-8">
		<form asp-action="EnviarInformacion" asp-controller="Contacto" method="post">
			<div class="mb-3">
				<label class="form-label">Email</label>
				<input type="Email" asp-for="Email" class="form-control" />
			</div>
			<div class="mb-3">
				<label class="form-label">Comentarios</label>
				<textarea class="form-control" asp-for="Comentario" rows="4"></textarea>
			</div>
			<button class="btn btn-primary">Enviar</button>
		</form>
	</div>
	<div class="col-4">
		<h3 class="text-center">Enviar informacion al correo capturado.</h3>
		<p></p>
	</div>
</div>

24CV WEB/Views/Formulario/Contacto.cshtml
@model _24CV_WEB.Models.InformacionViewModel

<div class="row">
	@if (TempData["Nombre"] != null && TempData["Apellidos"] != null && TempData["Email"] != null && TempData["FechaNacimiento"] != null && TempData["Turno"] != null && TempData["Comentarios"] != null)
	{
		<div class="alert alert-success">
			<h3 class="text-sm-center">Se ha recibido la informacion del correo @TempData["Email"]</h3> <br>
			<p class="text-sm-center">@TempData["Nombre"]</p>
			<p class="text-sm-center">@TempData["Apellidos"]</p>
			<p class="text-sm-center">@TempData["Email"]</p>
			<p class="text-sm-center">@TempData["FechaNacimiento"]</p>
			<p class="text-sm-center">@TempData["Turno"]</p>
			<p class="text-sm-center">@TempData["Comentarios"]</p>
		</div>
	}


	<div class="col-12">
		<h2 class="text-center">Formulario de Contacto</h2>
		<p class="text-center"></p>
	</div>
	<div class="col-8">
		<form asp-action="EnviarInformacion" asp-controller="Formulario" method="post">
			<div class="mb-3">
				<label class="form-label">Nombre</label>
				<input type="text" asp-for="Nombre" class="form-control" />
			</div>
			<div class="mb-3">
				<label class="form-label">Apellidos</label>
				<input type="text" asp-for="Apellidos" class="form-control" />
			</div>
			<div class="mb-3">
				<label class="form-label">Email</label>
				<input type="Email" asp-for="Email" class="form-control" />
			</div>
			<div class="mb-3">
				<label class="form-label">Fecha de Nacimiento</label>
				<input type="date" asp-for="FechaNacimiento" class="form-control" />
			</div>
			<div class="mb-3">
				<label class="form-label">Turno</label>
				<select asp-for="Turno" class="form-select">
					<option value="Matutino">Matutino</option>
					<option value="Vespertino">Vespertino</option>
				</select>
			</div>
			<div class="mb-3">
				<label class="form-label">Comentarios</label>
				<textarea class="form-control" asp-for="Comentarios" rows="4"></textarea>
			</div>
			<button class="btn btn-primary">Enviar</button>
		</form>
	</div>
	<div class="col-4">
		<h3 class="text-center">Enviar informacion al correo capturado.</h3>
		<p></p>
	</div>
</div>

24CV WEB/Views/Formulario/Template.cshtml
<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>Appointment Reminder Email Template</title>
    <meta name="description" content="Appointment Reminder Email Template">
</head>
<style>
    a:hover {
        text-decoration: underline !important;
    }
</style>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
    <table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8"
        <tr>
            <td>
                <table style="background-color: #f2f3f8; max-width:670px; margin:0 auto;" width="100%" border="0"
                       align="center" cellpadding="0" cellspacing="0">
                    <tr>
                        <td style="height:80px;">&nbsp;</td>
                    </tr>
                    <!-- Logo -->
                    <tr>
                        <td style="text-align:center;">
                            <a href="https://rakeshmandal.com" title="logo" target="_blank">
                                <img width="60" src="https://i.ibb.co/hL4XZp2/android-chrome-192x192.png" title="logo" alt="logo">
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td style="height:20px;">&nbsp;</td>
                    </tr>
                    <!-- Email Content -->
                    <tr>
                        <td>
                            <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0"
                                   style="max-width:670px; background:#fff; border-radius:3px;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);padding:0 40px;">
                                <tr>
                                    <td style="height:40px;">&nbsp;</td>
                                </tr>
                                <!-- Title -->
                                <tr>
                                    <td style="padding:0 15px; text-align:center;">
                                        <h1 style="color:#1e1e2d; font-weight:400; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">Appointment Reminder</h1>
                                        <span style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece;
                                        width:100px;"></span>
                                    </td>
                                </tr>
                                <!-- Details Table -->
                                <tr>
                                    <td>
                                        <table cellpadding="0" cellspacing="0"
                                               style="width: 100%; border: 1px solid #ededed">
                                            <tbody>
                                                <tr>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; border-right: 1px solid #ededed; width: 35%; font-weight:500; color:rgba(0,0,0,.64)">
                                                        Appointment ID:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056;">
                                                        ABC-101
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; border-right: 1px solid #ededed; width: 35%; font-weight:500; color:rgba(0,0,0,.64)">
                                                        Patient ID:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056;">
                                                        XYZ-101
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; border-right: 1px solid #ededed; width: 35%; font-weight:500; color:rgba(0,0,0,.64)">
                                                        Department:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056;">
                                                        Endoscopy
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed;border-right: 1px solid #ededed; width: 35%; font-weight:500; color:rgba(0,0,0,.64)">
                                                        Doctor Name:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056;">
                                                        Russell Walker
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px;  border-bottom: 1px solid #ededed; border-right: 1px solid #ededed; width: 35%;font-weight:500; color:rgba(0,0,0,.64)">
                                                        Appointment Date:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056;">
                                                        12<sup>th</sup> April 2019
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; border-right: 1px solid #ededed; width: 35%;font-weight:500; color:rgba(0,0,0,.64)">
                                                        Appointment Time:
                                                    </td>
                                                    <td style="padding: 10px; border-bottom: 1px solid #ededed; color: #455056; ">
                                                        11:00 AM
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding: 10px; border-right: 1px solid #ededed; width: 35%;font-weight:500; color:rgba(0,0,0,.64)">
                                                        Reason:
                                                    </td>
                                                    <td style="padding: 10px; color: #455056;">During an upper endoscopy, an endoscope is easily passed through the mouth and throat and into the esophagus, allowing the doctor to view the esophagus, stomach, and upper part of the small intestine.</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="height:40px;">&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td style="height:20px;">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="text-align:center;">
                            <p style="font-size:14px; color:#455056bd; line-height:18px; margin:0 0 0;">&copy; <strong>www.rakeshmandal.com</strong></p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>

24CV WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

24CV WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _24CV_WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_24CV_WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_24CV_WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ejemplos" asp-action="Index">Ejemplos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ejemplos" asp-action="Contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Contacto">Tarea Casa</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _24CV_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>