MiFormulario/Controllers/ValidacionesController.cs
using Microsoft.AspNetCore.Mvc;
using MiFormulario.Services.Contracts;
using MiFormulario.Models;

namespace MiFormulario.Controllers
{
    public class ValidacionesController : Controller
    {
        private readonly ICurriculumService _curriculumService;

        public ValidacionesController(ICurriculumService curriculumService)
        {
            _curriculumService = curriculumService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EnviarInformacion(Curriculum model)
        {

            string mensaje = "";
            //model.RutaFoto = "FakePath";

            if (ModelState.IsValid)
            {
                var response = _curriculumService.Create(model).Result;

                mensaje = response.Message;
                TempData["msj"] = mensaje;
                return RedirectToAction("Index");
            }
            else
            {
                mensaje = "Datos incorrectos";
                TempData["msj"] = mensaje;

                return View("Index", model);
            }

        }

        public IActionResult Lista()
        {
            return View(_curriculumService.GetAll());
        }
    }
}

MiFormulario/Views/Validaciones/Index.cshtml
@model MiFormulario.Models.Curriculum

<div class="row">
    @if (TempData["msj"] != null)
    {
        <div class="alert alert-success">
            @TempData["msj"]
        </div>
    }


    <div class="col-12">
        <h2 class="text-center">Ejemplo de envio de información</h2>
        <p class="text-center">Envío de formulario pasando datos de la vista al controlador.</p>
    </div>
    <div class="col-8">
        <form asp-action="EnviarInformacion" asp-controller="Validaciones" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input type="text" asp-for="Nombre" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Apellido Paterno</label>
                <input type="text" asp-for="ApellidoPaterno" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Apellido Materno</label>
                <input type="text" asp-for="ApellidoMaterno" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" asp-for="Email" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">CURP</label>
                <input type="text" asp-for="CURP" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de nacimiento</label>
                <input type="date" asp-for="FechaNacimiento" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">% Inglés</label>
                <input type="number" asp-for="PorcentajeIngles" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Foto</label>
                <input type="file" asp-for="Foto" class="form-control" />
            </div>
            <div class="mb-3">
                <input type="hidden" asp-for="RutaFoto" value="FakePath" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Dirección</label>
                <textarea class="form-control" asp-for="Dirección" rows="4"></textarea>
            </div>
            <button class="btn btn-primary" type="submit">Enviar</button>
        </form>

    </div>
    <div class="col-4">
        <h3 class="text-center">Enviar información al correo capturado</h3>
        <p>Se enviará un correo con la información capturada.</p>
    </div>
</div>

MiFormulario/Views/Validaciones/Lista.cshtml
@model IEnumerable<MiFormulario.Models.Curriculum>

<h1 class="text-center">Lista de curriculums</h1>

<div class="row">
    <div class="col-12">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellidos</th>
                    <th>Fecha Nacimiendo</th>
                    <th>CURP</th>
                    <th>Image Path</th>
                    <th>Foto</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.ApellidoPaterno</td>
                        <td>@item.FechaNacimiento</td>
                        <td>@item.CURP</td>
                        <td>@item.RutaFoto</td>
                        <td>
                            @if (!string.IsNullOrEmpty(item.RutaFoto))
                            {
                                <img src="~/Fotos/@item.RutaFoto" width="150" height="150">
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>